require 'tapout/reporters/abstract'
require 'tapout/reporters/breakdown'
require 'tapout/reporters/dotprogress'
require 'tapout/reporters/html'
require 'tapout/reporters/outline'
require 'tapout/reporters/progressbar'
require 'tapout/reporters/tap'
