require 'tapout/reporters/abstract'

require 'tapout/reporters/dot_reporter'
require 'tapout/reporters/pretty_reporter'
require 'tapout/reporters/turn_reporter'
require 'tapout/reporters/html_reporter'
require 'tapout/reporters/outline_reporter'
require 'tapout/reporters/progress_reporter'
require 'tapout/reporters/breakdown_reporter'
require 'tapout/reporters/tap_reporter'
require 'tapout/reporters/markdown_reporter'
